apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tmg8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-emsu-tenant/rhtap-demo-app/hacbs-test-project-tmg8@sha256:0d1f56d9005e66843aeb1e4893d5afaf4c41082b7ee0ceb7bd51d45727367e52
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
