apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tmg8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tmg8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tmg8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tmg8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tmg8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-emsu-tenant/rhtap-demo-app/hacbs-test-project-tmg8@sha256:71c566a8bbe2c354c7fb6cdbe096494a33f4e77d19da84807c9be40cde85898d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
